# Generated by Django 3.0.6 on 2020-06-01 11:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('1', 'Sunday'), ('2', 'Monday'), ('3', 'Tuesday'), ('4', 'Wednesday'), ('5', 'Thursday'), ('6', 'Friday'), ('7', 'Saturday')], max_length=15)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, unique=True, verbose_name='Nome')),
                ('description', models.CharField(default='', max_length=500, verbose_name='Descrição')),
                ('max_duration', models.IntegerField(choices=[(28, '28'), (57, '57'), (117, '117')], default=28, verbose_name='Duração Máxima')),
                ('first_emission_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Primeira emissão')),
                ('comes_normalized', models.BooleanField(default=False, help_text='Caso o programa tenha certas partes propositadamente baixas, selecciona esta opção.', verbose_name='Não aplicar alteração dinâmica de volume')),
                ('ignore_duration_adjustment', models.BooleanField(default=False, help_text=' Caso o programa não deva ter a sua duração ajustada automaticamente, selecciona esta opção.', verbose_name='Ignorar ajuste automático de duração')),
                ('is_external', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('A', 'Activo'), ('H', 'Em hiato'), ('T', 'Terminado')], default='A', max_length=15, verbose_name='Estado')),
            ],
        ),
    ]
