# Generated by Django 3.0.6 on 2020-06-02 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_auto_20200601_1108'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Day',
            new_name='Slot',
        ),
    ]
