# Generated by Django 3.0.8 on 2020-07-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_auto_20200602_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='rss_feed_status',
            field=models.BooleanField(default=False, verbose_name='Status do upload automático com Feed RSS'),
        ),
        migrations.AddField(
            model_name='program',
            name='rss_feed_url',
            field=models.CharField(default='', max_length=1024, verbose_name='Endereço do Feed RSS'),
        ),
    ]
