# Generated by Django 3.0.8 on 2020-07-30 19:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_slot_is_rerun'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Data da coleção de contagens')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='Hora de início da coleção de contagens')),
                ('listener_stats_str', models.CharField(default='', max_length=360, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Contagens de ouvintes (período 2 min)')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.Slot', verbose_name='Slot correspondente às contagens, se existir')),
            ],
        ),
    ]
