# Generated by Django 3.0.8 on 2020-08-02 11:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_slot_is_rerun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='first_emission_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Primeira emissão'),
        ),
    ]
