# Generated by Django 3.0.7 on 2020-06-25 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keydoc',
            old_name='doc',
            new_name='doc_hash',
        ),
    ]
