# Generated by Django 3.0.6 on 2020-06-01 11:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('is_staff', models.BooleanField(default=False)),
                ('author_name', models.CharField(max_length=75, unique=True, verbose_name='Author name')),
                ('full_name', models.CharField(max_length=100, unique=True, verbose_name='Full name')),
                ('id_type', models.CharField(choices=[('CC', 'Citizen Card'), ('PP', 'Passport'), ('CCo', 'Driving License'), ('TR', 'Residence Title')], max_length=3, verbose_name='ID Type')),
                ('id_number', models.CharField(max_length=30, unique=True, verbose_name='ID Number')),
                ('ist_student_options', models.CharField(choices=[('Y', 'Yes'), ('N', 'Ex-Student'), ('E', 'External')], max_length=1, verbose_name='IST Student')),
                ('ist_student_number', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='IST Student Number')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='Phone')),
                ('state', models.CharField(choices=[('MM', 'Membro'), ('CO', 'Colaborador'), ('CH', 'Colaborador Honorário'), ('EM', 'Ex-membro')], default='MM', max_length=2, verbose_name='State')),
                ('entrance_date', models.DateField(default=django.utils.timezone.now, verbose_name='Entrance Date')),
                ('department', models.CharField(choices=[('AD', 'Administração'), ('CM', 'Comunicação e Marketing'), ('PR', 'Programação'), ('TL', 'Técnico e Logístico'), ('NA', 'Não Atribuído')], default='NA', max_length=2, verbose_name='Department')),
                ('role', models.CharField(choices=[('PR', 'Presidente'), ('SE', 'Secretário'), ('TE', 'Tesoureiro'), ('DI', 'Director'), ('EL', 'Elemento'), ('NA', 'Não Atribuído')], default='NA', max_length=2, verbose_name='Role')),
                ('notes', models.TextField(blank=True, default=None, null=True, verbose_name='Notes')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('exit_date', models.DateField(blank=True, default=None, null=True, verbose_name='Exit Date')),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
